### ISSUE TITLE
Super broken

### ISSUE THREAD

**Issue by JoshuaDRose** [derektata/lorem.nvim#1]
Does not register as a command at all.
Does not work entirely, i recommend you should put a disclaimer stating that this plugin is broken and does not work, as 'under maintainence' does not really explain that it is broken. 
Cheers.

**Comment by derektata** [comment]
Which version of Neovim are you using? If it is an older build, it will not work and I apologize about that. I should have noted that in the docs. 

If it is a newer build, it should work. Here's an example video below: 
https://user-images.githubusercontent.com/63433989/197543858-1ef693b2-04ce-42e4-b754-d7d01ebcc03a.mp4
