### ISSUE TITLE
[BUG] No output when `number < 3`

### ISSUE THREAD

**Issue by midrare** [derektata/lorem.nvim#3]
**To reproduce**
 1. `:lua print(require("lorem").gen_words(1))`
 2. Observe that nothing is outputted

**Notes**
This happens with any number `< 3`.

---

**Config `(lazy.nvim)`**
```lua
return {
  'derektata/lorem.nvim',
  lazy = true,
  opts = {
    sentenceLength = 'mixedShort',
    comma = 0,
  },
}
```

**Comment by derektata** [comment]
I've updated the lower bounds for mixedShort to fix this (See [1cec3b3](https://github.com/derektata/lorem.nvim/commit/1cec3b3c1798f0c6b4bbce6405b12be39a309597) for more info)

![output](https://github.com/derektata/lorem.nvim/assets/63433989/0102aaef-84d4-4557-bed1-6a106aed0acb)
